### ISSUE TITLE
LTspice executable not settable

### ISSUE THREAD

**Issue by aanas-sayed** [nunobrum/PyLTSpice#104]
The LTspice path inside the PyLTSpice.sim.ltspice_simulator module doesn't allow the user to set the name of the executable only the folder. The executable file name has changed in the newer version of LTspice and thus breaks:
```
spice_exe = ["wine", os.environ['LTSPICEFOLDER'] + "/XVIIx64.exe"]
```
I tried doing a work around by creating a custom LTspice class, but this doesn't work for some reason. Apologies if I have made an oversight. 
```
from PyLTSpice.sim.ltspice_simulator import LTspice
class CustomLTspice(LTspice):
    spice_exe = [
        "wine",
        "/home/aanas/.wine/drive_c/Program Files/ADI/LTspice/Ltspice.exe",
        "-b",
    ]
    process_name = "Ltspice.exe"
```
Only way I got it running was by reloading the module with the modified class:
```
ltspice_module = sys.modules["PyLTSpice.sim.ltspice_simulator"]
ltspice_module.LTspice = CustomLTspice
```
I believe the LTSPICECOMMAND for "/XVIIx64.exe" should be an environment variable

**Comment by aanas-sayed** [comment]
Dear Nunobrum,

Thank you by the way for the awesome library. It has been very helpful and removed a lot of potential headaches.

I've given it a go at fixing the issue myself, I'm not sure I have the permission to create a new branch and push the new commit but here's the snippet:
```
class LTspice(Simulator):
    ...
    """Searches on the any usual locations for a simulator"""
    if sys.platform == "linux":
        spice_folder = os.environ.get("LTSPICEFOLDER")
        spice_executable = os.environ.get("LTSPICEEXECUTABLE")

        if spice_folder and spice_executable:
            spice_exe = ["wine", os.path.join(spice_folder, spice_executable)]
            process_name = spice_executable
        elif spice_folder:
            spice_exe = ["wine", os.path.join(spice_folder, "/XVIIx64.exe")]
            process_name = "XVIIx64.exe"
        elif spice_executable:
            default_folder = os.path.expanduser(
                "~/.wine/drive_c/Program Files/LTC/LTspiceXVII"
            )
            spice_exe = ["wine", os.path.join(default_folder, spice_executable)]
            process_name = spice_executable
        else:
            default_folder = os.path.expanduser(
                "~/.wine/drive_c/Program Files/LTC/LTspiceXVII"
            )
            spice_exe = ["wine", os.path.join(default_folder, "XVIIx64.exe")]
            process_name = "XVIIx64.exe"

    ...
```

Thank you for taking your time to look into this issue, and I hope to hear your thoughts on this.

Thanks,
Aanas

**Comment by nunobrum** [comment]
Included in last push
