### ISSUE TITLE
PyLTSpice 4.1.2: `create_netlist` uses undefined variable `cmd_line_switches`

### ISSUE THREAD

**Issue by gudnimg** [nunobrum/PyLTSpice#124]
Got this error when upgrading PyLTSpice to latest version.

This is the problematic line: https://github.com/nunobrum/PyLTSpice/blob/8db95bcb150cdbb3da07a7a3cd9d8afa6fb0829a/PyLTSpice/sim/ltspice_simulator.py#L182

I would submit PR but I'm not sure if it's OK to remove `cmd_line_switches`?

**Comment by gudnimg** [comment]
![image](https://github.com/nunobrum/PyLTSpice/assets/8218499/7c633ad1-c765-491c-ba1f-df7097d607ff)

**Comment by gudnimg** [comment]
Looks like this change broke things: https://github.com/nunobrum/PyLTSpice/pull/121 🤔

**Comment by nunobrum** [comment]
Yes. I see the problem. I've accepted a pull-request without really making all the necessary verifications.
Anyway, 
I've already corrected the problem and was just finishing other verifications before committing a brand new PyLTspice.

**Comment by gudnimg** [comment]
@nunobrum Awesome :) I had some changes I wanted to contribute, but wanted to test on latest PyLTspice first.

**Comment by gudnimg** [comment]
I see the issue is fixed on spicelib side so I'm closing this issue
