### ISSUE TITLE
PyLTSpice.LTSteps does not have function LTSpiceLogReader

### ISSUE THREAD

**Issue by bilal-at-reach** [nunobrum/PyLTSpice#132]
Just did a fresh install and have the issue that the module can't be found to import. 
"PyLTSpice.LTSteps does not have function LTSpiceLogReader"

Downgrading to v 4.1.1 worked

**Comment by nunobrum** [comment]
Hello @bilal-at-reach 
the LTSpiceLogReader was moved to a subfolder "logs" and this was not reflected in the documentation.

Anyway, I just pushed a new version were you can either use:
`from PyLTSpice.log.ltsteps import LTSpiceLogReader`
or simply
`from PyLTSpice import LTSpiceLogReader`

Thanks for forgiving this lapse,
Best Regards,
Nuno
