### ISSUE TITLE
example sim_runner_callback_example.py needs the "rich" module

### ISSUE THREAD

**Issue by viisatadi** [nunobrum/PyLTSpice#136]
Given that the examples use this module, it should be an included requirement

Error message is:
```
python sim_runner_callback_example.py
Traceback (most recent call last):
  File "sim_runner_callback_example.py", line 3, in <module>
    from rich.logging import RichHandler
ModuleNotFoundError: No module named 'rich'
```

**Comment by nunobrum** [comment]
I'll probably remove this feature from the example on the next version. 
I prefer not to add yet another dependency. I'll close this issue when the  next version is released.

**Comment by nunobrum** [comment]
The import rich has now a try: except ImportError: clause around it. If it is not found, then it is not used.
