### ISSUE TITLE
Vin is not label in Batch_Test.asc

### ISSUE THREAD

**Issue by 1taroh** [nunobrum/PyLTSpice#137]
Hello.

In README.md, `V(Vin)` is saved but `Vin` is not a label in [Batch_Test.asc](https://github.com/nunobrum/PyLTSpice/blob/master/examples/testfiles/Batch_Test.asc).
https://github.com/nunobrum/PyLTSpice/blob/bcdf5c36319d55fc69d65c3704dea745ea5fc659/README.md?plain=1#L149-L152

Actually, `in` is the correct label.

![image](https://github.com/nunobrum/PyLTSpice/assets/65810214/5dafab52-d29e-40c7-b23f-fde0532f07af)

**Comment by nunobrum** [comment]
Aligned all examples on the README.md with the code existing on the examples folder.

**Comment by 1taroh** [comment]
thank you so much!!
