### ISSUE TITLE
SpiceEditor path detection problem

### ISSUE THREAD

**Issue by azbiciak** [nunobrum/PyLTSpice#140]
![image](https://github.com/nunobrum/PyLTSpice/assets/51076401/e0e362e3-5f14-4441-969c-db4cd1561427)
![Annotation 2024-05-16 145610](https://github.com/nunobrum/PyLTSpice/assets/51076401/f6aa9319-e8d4-401a-855b-7bd6a23aae90)

The same path, that works for SimCommander doesn't work for SpiceEditor. Why is it the case?

**Comment by nunobrum** [comment]
Hi there,

SpiceEditor is expecting to receive a SPICE text file format. 
The SimCommander can receive an LTSpice schematic, and it will generate automatically the netlist. 
This was changed because the netlist generation does not work well in Mac OSX.
