### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by brianbienvenu** [nunobrum/PyLTSpice#142]
When Dropbox is syncing in the background, I experience frequent crashes, approximately every 5 runs. Re-running the same netlist will usually work.

```
2024-07-17 12:35:38,736        run_task: 90         print_info    ERROR RunTask #8:Simulation Raw file or Log file were not found
```

The only output in the .log file is: `Could not open input deck for reading: <snip>.log`

If I disable Dropbox, this issue goes away. Acknowledging this is probably an issue with Dropbox looking at/holding on to files which are being rapidly edited, are there any workarounds for this which can be implemented?

**Comment by nunobrum** [comment]
Could move your simulation files to somewhere outside the scope of your dropbox sync. You can specify the working directory using the output_folder parameter on the SimRunner constructor.
