### ISSUE TITLE
LTSpice Netlist referencing binary library (.sub) file

### ISSUE THREAD

**Issue by renegadephysicist** [nunobrum/PyLTSpice#143]
Hello,

Great work on this fantastic project!

I have a netlist file that references a binary library (file extension .sub) e.g.

`.lib ltm4700 `

this finds a file called ltm4700.sub but fails attempting to find its text encoding (understandably as it’s a binary file) when attempting to create a SpiceCircuit from it. Looking at the examples several files are referred this way 
E.g. `.lib ADI1.lib` but these are ascii files not proprietary binaries.

I’m not interested in changing this .sub file but rather modifying the circuitry surrounding it described in the netlist.

Maybe I’m missing something basic but is this possible?

LTSpice 24
Spicelib latest main branch
Pyltspice latest main branch

**Comment by nunobrum** [comment]
Hello,

I am not sure I understand your issue correctly. Is it that  spicelib/PyLTSpice crashes because of a library in binary format and you want to avoid crashing. 
It would be helpful if you send me the crash log so I can see where exactly it is crashing.

I am a bit puzzled because normally the PyLTSpice/spicelib don't open libraries, except if they can't find what they are looking for.

**Comment by renegadephysicist** [comment]
Basically I'm trying to run this code, on any of the spice models found [here for LTM4700](https://www.analog.com/en/products/ltm4700.html#reference-designs). This[ asc is the one I used below.](https://www.analog.com/media/en/simulation-models/LTspice-demo-circuits/LTM4700_DC2784A-B.asc)

```
import os

from PyLTSpice import AscEditor, SimRunner
from PyLTSpice.sim.sim_stepping import SimStepper

runner = SimRunner(parallel_sims=4, output_folder='../temp2')
netlist = AscEditor("./LTM4700_DC2784A-B.asc")

Stepper = SimStepper(netlist, runner)
```

The error I'm getting is:

```
Traceback (most recent call last):
  File ".\PyLTSpice\examples\sim_stepper_example_new.py", line 15, in <module>
    netlist = AscEditor(".\LTM4700_DC2784A-B.asc")
  File ".\.venv\lib\site-packages\spicelib\editor\asc_editor.py", line 74, in __init__
    self.reset_netlist()
  File ".\.venv\lib\site-packages\spicelib\editor\asc_editor.py", line 172, in reset_netlist
    component.attributes["_SUBCKT"] = self._get_subcircuit(symbol)
  File ".\.venv\lib\site-packages\spicelib\editor\asc_editor.py", line 298, in _get_subcircuit
    answer = SpiceEditor.find_subckt_in_lib(lib_path, model)
  File ".\.venv\lib\site-packages\spicelib\editor\spice_editor.py", line 1026, in find_subckt_in_lib
    encoding = detect_encoding(library)
  File ".\.venv\lib\site-packages\spicelib\utils\detect_encoding.py", line 82, in detect_encoding
    raise EncodingDetectError(f"Unable to detect encoding on log file: {file_path}")
spicelib.utils.detect_encoding.EncodingDetectError: Unable to detect encoding on log file: C:\Users\jj\AppData/Local/LTspice/lib\sub\LTM4700.sub
```

**Comment by nunobrum** [comment]
Hello @renegadephysicist,

I have just created a branch called "encrypted_libraries" in spicelib that tries to solve this problem. 
Can you try this checking it out, adding it your PYTHONPATH and testing it.

Cheers,
Nuno

**Comment by nunobrum** [comment]
Version 5.4.0 addresses this issue.
