### ISSUE TITLE
Reading log files

### ISSUE THREAD

**Issue by hgmolina** [nunobrum/PyLTSpice#144]
When _PyLTSpice\log\ltsteps.py_ is trying to  **detect_encoding(log_filename, "Circuit:")** (line 319) it's only looking for the first line in the log file. But currently, LTSpice is generating logs like this (Circuit is in the second line):
<img width="467" alt="{22D721FF-AE3D-4960-A4E0-90F075AB2637}" src="https://github.com/user-attachments/assets/20528f19-1a00-478c-8df5-7b6498cb4629">
and I'm getting this error:
**f"Expected string \"{expected_str}\" not found in file:{file_path}"**

**Comment by nunobrum** [comment]
I guess this is a new feature of LTspice. Thanks for the heads up.
I'll fix this as soon as possible. If you already fixed it yourself, feel free to make a pull-request.

**Comment by hgmolina** [comment]
I don't have git tools from the remote developer pc. In \PyLTSpice\utils\detect_encoding.py  (line 62), I've changed this:
 _if not lines[0].startswith(expected_str):_
for this
_if not lines[0].startswith(expected_str )and not lines[1].startswith(expected_str):_

**Comment by nunobrum** [comment]
Thanks! Good to know you are not blocked.
I'll close this as soon as I publish the fix to PyPi

**Comment by nunobrum** [comment]
Version 5.4.0 addresses this issue.
