### ISSUE TITLE
time.clock() deprecated in Python 3.8

### ISSUE THREAD

**Issue by thomakamaru** [nunobrum/PyLTSpice#20]
Hi,
`time.clock()` is no longer supported in Python 3.8, therefore a problem occurs in LTSpiceBatch.py.

See:
https://docs.python.org/3/whatsnew/3.8.html 

Using
`time.process_time()`
seems to be working.

Cheers
Thomas

**Comment by nunobrum** [comment]
Thanks for your contribution.
I'm preparing a major upgrade into the LTSpiceBatch and will take into consideration your input.

Best Regards,
Nuno
