### ISSUE TITLE
Introduce Github Workflow for Unittest

### ISSUE THREAD

**Issue by akaeba** [nunobrum/PyLTSpice#25]
Hello Nuno,

a next interesting point for the project would be a unit test, where functionality for the python packages are automatically with some test cases are checked. For the sweep_iterators.py I like to setup the github workflow. What do you think?

Best Regards,
Andreas

**Comment by nunobrum** [comment]
Yes!  It’s a good idea the unit test. 
There are a few test codes on the tests folder, but not really using the unittest lib. 
It would be an improvement to have it.

**Comment by akaeba** [comment]
Update [Pull Request](https://github.com/nunobrum/PyLTSpice/pull/28)

**Comment by nunobrum** [comment]
Thanks. I have accepted your pull request
