### ISSUE TITLE
_getline_startingwith in SpiceEditor.py returns wrong reference designators

### ISSUE THREAD

**Issue by sundr007** [nunobrum/PyLTSpice#34]
Use case: Search for R11 in a netlist that includes both R112 and R11.  I find that this function returns R112 instead of R11.  I changed the following line and the issue was resolved.  I encountered this issue while I was trying to change the value of R11 and instead it changed the value of R112.

if line_upcase.startswith(substr_upper):

becomes

if line_upcase.startswith(substr_upper) and "%s "%substr_upper in line.upper():

**Comment by nunobrum** [comment]
Hi @sundr007 . Thanks for highlighting this issue.
I have looked at the code, and if you are already use a version that uses the _first_token_upped() function, then you can replace the line 

if line_upcase.startswith(substr_upper):

by

if line_upcase == substr_upper:

I have just pushed a version with this correction.
