### ISSUE TITLE
Application Example in LTSpiceBatch.py fails

### ISSUE THREAD

**Issue by danielphili** [nunobrum/PyLTSpice#39]
Hi again, Nuno!

I am wondering about the following: When using the given example at the top of the LTSpiceBatch.py, the generation of self.circuit_radic will point to what would be the root directory in Linux - actually, I am not sure what this is interpreted as on Windows. Anyway - it is not pointing to the same directory as the python script and the LTSpice schematic file in this case and throws a "no permission" error.
A test showed that the following if-condition helps:
'''
if circuit_path == '':
            circuit_path = '.'
'''

Best regards,

Daniel

**Comment by nunobrum** [comment]
I have committed a version that makes the following implementation
```
        if self.file_path == '':
            self.file_path = os.path.abspath(os.curdir)
```
I hope that this will fix for all operating systems.
