### ISSUE TITLE
Deprecated examples in readme.md

### ISSUE THREAD

**Issue by fewei** [nunobrum/PyLTSpice#40]
Hi,

I'm not used to the github/pullrequest/... workflow, but I'd like to contribute my stuff to this awesome package.
I couldn't run the examples without change. I'm using Python 3.9.

Example1
------------
In https://github.com/nunobrum/PyLTSpice#ltspice_rawreadpy 
```python
from matplotlib import plot
#change to
from matplotlib import pyplot as plt
```

Example 2
-------------
Next example does not work at all anymore. I guess code changed a lot
```python
raw, log = LTC.run()
```
I'd like to request this as a feature. It makes so much more easy for people who don't want to deal with events and can spare the time. Either raw/log file or any other id
```python
run1 = LTC.run()
# ...
run2 = LTC.run()
LTC.wait_completion()

ltr1 = LTSpiceRawRead(run1)
# ...
ltr1 = LTSpiceRawRead(run2)

```

**Comment by nunobrum** [comment]
Hi @fewei ,

I've just committed a version that fixes all your remarks. As for your request on Example 2, I do think what you are proposing makes sense, so, I have implemented something that can either operate with a callback and not. Now the run function returns the Task Object, and this allows to do what you are proposing, but, you need to write this in this format,
``` python
run1 = LTC.run()
LTC.wait_completion() # Now this could be skipped
run1raw, run1log = run1.wait_return()  # will return raw and log. It waits if the task is not finished.
ltr1 = LTSpiceRawRead(run1raw)
```
I'm closing the ticket. If this doesn't correspond to what you were asking, please feel free to reopen this issue.
