### ISSUE TITLE
Read Log Files in Operating Point

### ISSUE THREAD

**Issue by Eymay** [nunobrum/PyLTSpice#44]
Not sure if it is possible as I didn't see it in the docs but I would like to see gm value of a mosfet in op simulation. The gm and more parameters are saved in .log file.

Support for Semiconductor Device Operating Points in the log file.
![image](https://user-images.githubusercontent.com/20779470/151669764-0b57ca18-e975-4bf8-b7d9-65e41a223da3.png)

**Comment by nunobrum** [comment]
Yes, it is possible. There is a module that does it. 
The https://github.com/nunobrum/PyLTSpice/blob/master/PyLTSpice/LTSpice_SemiDevOpReader.py
reads an operating point log file and reads all the information and returns the data in the form of a dictionary of dictionaries.
```
from PyLTSpice.LTSpice_SemiDevOpReader import opLogReader
data = opLogReader('simulation logfile.log')
gm = data['BSIM4 MOSFETS']['m16']['Gm']  # getting the GM value of transistor m16
mos_transistors =data['BSIM4 MOSFETS']
dict_with_all_gms = { ref : mos_transistors[ref]['Gm'] for ref in data mos_transistors }
```

**Comment by nunobrum** [comment]
Seems to have worked. Closing the issue
