### ISSUE TITLE
Call to add_LTspiceRunCmdLineSwitches result in error when subsequently calling run()

### ISSUE THREAD

**Issue by Mario-ehv** [nunobrum/PyLTSpice#45]
I'm trying to add LTSpice command line switches using the add_LTspiceRunCmdLineSwitches(self, *args) function of the PyLTSpice.LTSpiceBatch.SimCommander class.

When using add_LTspiceRunCmdLineSwitches subsequent calls to the run() function fail with the following error:
TypeError: can only concatenate list (not "tuple") to list.

I'm using PyLTSpice in a python3 environment. The problem seems to be related to the fact that the function argument *arg used in add_LTspiceRunCmdLineSwitches is (always) being transferred as being of type tuple (not as list)

As temporary workaround I'm now using add_LTspiceRunCmdLineSwitches(self, args), hence the asterix before args removed.
This works in case of using a single command line argument (might fails in case of more than one command line arguments are used).

**Comment by nunobrum** [comment]
Interesting... I believe that this wasn't a problem before.
Anyways... I think this can be quickly solved by replacing the line the add_LTspiceRunCmdLineSwitches() from
`cmdline_switches = args`
to 
`cmdline_switches = list(args)`
I'll integrate this in the next release.
