### ISSUE TITLE
cannot loading the SimCommander() function correctly

### ISSUE THREAD

**Issue by MrLinNing** [nunobrum/PyLTSpice#49]
Could you please help me solve this problem? Thanks for your help!
![image](https://user-images.githubusercontent.com/24288811/157902823-7871e99d-e557-4d2c-a4d6-cf16ef902011.png)

**Comment by nunobrum** [comment]
Hello,

I believe the problem is that you are both declaring a raw string by prefixing it with the letter 'r' and then double back-slashing. Please chose one or the other method. I believe the both might be causing problems.
