### ISSUE TITLE
Issue using Single point AC simulation

### ISSUE THREAD

**Issue by Pimss** [nunobrum/PyLTSpice#52]
I am  working on an AC circuit simulation with a single frequency point at the time and I have encontered a bug in the LTSpiceRawRead function. Here is a small python file and netlist file to replicate the issue

**netlist file:** simple_net.net
```shell
Title_file
c1 1 0 1p
c2 1 0 1p
vin 1 0 ac 1 dc 0
.ac dec 1 10 10
.probe
.end
```

**python file**: lts_bug_exemple.py
```python
from PyLTSpice.LTSpiceBatch import SimCommander
from PyLTSpice.LTSpice_RawRead import LTSpiceRawRead
from matplotlib import pyplot as plt
from numpy import abs, pi

file_net = "simple_net.net"
LTC = SimCommander(file_net)
LTC.run()
LTC.wait_completion()

# Sim Statistics
print('Successful/Total Simulations: ' + str(LTC.okSim) + '/' + str(LTC.runno))

raw_out_file = file_net[:-4] + "_1.raw"
LTR = LTSpiceRawRead(raw_out_file)

print(LTR.get_trace_names())
print(LTR.get_raw_property())

list_data = ["I(Vin)", "V(1)", "frequency"]
dict_out = {}
for key in list_data:
    dict_out[key] = LTR.get_trace(key)
    
steps = LTR.get_steps()
current_freq = dict_out["frequency"].get_wave()
current_z = dict_out["V(1)"].get_wave() / abs(dict_out["I(Vin)"].get_wave())
plt.plot(current_freq, current_z, label="Impedance 1-0")
plt.xscale('log')
plt.yscale('log')
plt.legend()
plt.grid(True)
plt.show()
```
These files give me the following error:
```
Found Numpy. WIll be used for storing data
Wed Jun 15 17:21:33 2022 : Starting simulation 1
Wed Jun 15 17:21:33 2022: Simulation Successful. Time elapsed 00:00:00:

No Callback
Successful/Total Simulations: 1/1
Normal access
Traceback (most recent call last):
  File "ltspice_exemple.py", line 56, in <module>
    LTR = LTSpiceRawRead(raw_out_file)
  File "C:\Tools\Dev\Anaconda2\envs\myenv\lib\site-packages\PyLTSpice\LTSpice_RawRead.py", line 672, in __init__
    var.set_pointB16(point, value)
  File "C:\Tools\Dev\Anaconda2\envs\myenv\lib\site-packages\PyLTSpice\LTSpice_RawRead.py", line 279, in set_pointB16
    self.data[n] = complex(re, im)
TypeError: can't convert complex to float
```
Note that if the line `.ac dec 1 10 10` in file ***simple_net.net***  is changed to `.ac dec 10 10 100k`, no bug is raised and the program is working.

If you have any element that may help in solving this issue, please let me know.

**Comment by nunobrum** [comment]
I simulated your case and I understand where is the problem. The present code is assuming that any simulation with only one sample point is a Operation Point (.OP) simulation.
I will have to test other ways of detecting this, so, this will require a bit more time.
I'll try to have this fixed till next Monday the latest.

**Comment by nunobrum** [comment]
@Pimss 
I have just committed a version that fixes the issue that you have found. 
Now using the "forward" flag to differentiate between Operating Points and other simulations.
Please let me know if it fixes your problem. 
Meanwhile, while testing it, I have found a weird behaviour on the steps files generated. Not always they are consistently generated and this causes problems to my script. I have introduced some "workarounds" but they not always work.

**Comment by Pimss** [comment]
I just used the latest commit on my small and large code exemple and it is working. Thank you very much !
