### ISSUE TITLE
RawRead doesn't currently support complex data such as from AC analysis.

### ISSUE THREAD

**Issue by l-johnston** [nunobrum/PyLTSpice#8]
# Issue
The existing LTSpiceRawRead only supports analysis types, such as TRAN, that produce real data. AC analysis produces complex data and is a significant use case.

# Potential solution - l-johnston@b32ceb9f53bebed3fcf372d43ef900dad090a2e7
I propose extending LTSpiceRawRead to support complex data. I show one way to do this in the referenced branch. I added the class RawRead that adds support for complex while keeping the original data structures, methods and API.

# Request
Review the proposed solution and provide feedback.

**Comment by nunobrum** [comment]
Integrated solution implemented by l-johnston
