### ISSUE TITLE
Invalid script entry point when installing with pip 23.12

### ISSUE THREAD

**Issue by ToInoJo** [nunobrum/PyLTSpice#93]
When I install the library using pip, there is an error message showing up.
![image](https://user-images.githubusercontent.com/93261527/237050960-dbef5223-0edb-45f9-8071-89679b567f12.png)

Which seems to have something to do with the way it's packaged for pip.

**Comment by VV-Cephai** [comment]
I have the same issue, using PIP 23.1.2 when trying to install version 4.0 of PyLTspice.
Installing version 3.1 of PyLTspice works.

**Comment by nunobrum** [comment]
Can you please try if it works now. I have tested in Windows and it it works well.

**Comment by ToInoJo** [comment]
Now it tries to build a numpy 1.21 that seems to not be compatible with either Python 3.10 or my Python installation, which gives an error building wheels for numpy. I have numpy 1.23 installed on my Windows machine.

**Comment by nunobrum** [comment]
Yes. I already received a notification about that. I’ll fix that tomorrow.

**Comment by nunobrum** [comment]
I've pushed a version that should get rid of the version impositions. However, I do have a few incompatibility issues between versions of numpy scipy and matplotlib. I'm no longer imposing any version on any of these packages.
There might be some deprecation warnings on the help command line tools that I bundle together with the package, but, I think these are less important.
Please let me know if it still causes problems for you.

**Comment by nunobrum** [comment]
I've tested in Windows 10 with Python 3.11 and it seems to be working well
