### ISSUE TITLE
from PyLTSpice.LTSteps import LTSpiceLogReader not working

### ISSUE THREAD

**Issue by smniessi** [nunobrum/PyLTSpice#99]
When trying to import "from PyLTSpice.LTSteps import LTSpiceLogReader" I get the following error:

Exception has occurred: EncodingDetectError
Expected string "Circuit:" not found in file:SpiceBatch.log
  File "_---my path---_", line 4, in <module>
    from PyLTSpice.LTSteps import LTSpiceLogReader
PyLTSpice.utils.detect_encoding.EncodingDetectError: Expected string "Circuit:" not found in file:SpiceBatch.log

I am working with the newest PyLTSpice 4.0.2. When I downgrade to Version 3.1 it works perfectly.

**Comment by nunobrum** [comment]
This was fixed in the latest push
